[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "2024"
OPENAI_API_KEY = "${OPENAI_API_KEY}"
ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
LANGSMITH_API_KEY = "${LANGSMITH_API_KEY}"
LANGSMITH_TRACING = "true"
LANGCHAIN_TRACING_V2 = "true" 