[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "2024"
OPENAI_API_KEY = "${OPENAI_API_KEY}"
ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
LANGSMITH_API_KEY = "${LANGSMITH_API_KEY}"
LANGSMITH_TRACING = "true"
LANGCHAIN_TRACING_V2 = "true"
LANGSMITH_ENDPOINT = "https://api.smith.langchain.com"
LANGSMITH_PROJECT = "langgraph-react-mcp-chat"
LANGSMITH_REQUEST_TIMEOUT = "30000" 